[[language]]
name = "python"
language-servers = []
roots = ["pyproject.toml"]

[[language]]
name = "go"
language-servers = []

[[language]]
name = "cpp"
language-servers = []
indent = {tab-width=4, unit="    "}
