[env]
term = "alacritty"
[window]
option_as_alt = "Both"
[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.cursor]

[colors.selection]

[colors.normal]
black = "#090618"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#DCD7BA"

[colors.bright]
black = "#727169"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#C8C093"
