[[language]]
name = "python"
language-servers = ["scls","pyright"]
file-types = ["py", "pyi"]
roots = ["pyproject.toml"]
formatter = {command = "black", args=["-", "--quiet"]}
auto-format = true

[[language]]
name = "go"
language-servers = ["scls","gopls"]
file-types = ["go"]


[[language]]
name = "html"
language-servers = ["emmet-ls", "tailwindcss-ls"]
formatter = {command = "prettier", args = ["--parser", "html"]}
file-types = ["html"]

[[language]]
name = "templ"
language-servers = ["templ","emmet-ls",  "tailwindcss-ls"]
file-types = ["templ"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
indent = {tab-width=4, unit="    "}

# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"


[language-server.scls.config]
max_completion_items = 10     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = false  # enable "unicode input"
feature_paths = true          # enable path completion

[language-server.tailwindcss-ls]
config = { userLanguages = { templ = "html", "*.templ" = "html" } }

[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]
