# Slow app run fix
exec-once =  dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = ~/dotfiles/hypr/xdg_fix.sh
# Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Base
exec-once = udiskie & hyprpaper
exec-once = hypridle & appimaged
exec-once = sleep 2s && waybar & swaync
#Desktop
exec-once = hyprctl dispatch exec [workspace 1 silent] "alacritty -e fish -c 'tmux attach || tmux'"
exec-once = hyprctl dispatch exec [workspace 2 silent] "firefox --new-window"
exec-once = hyprctl dispatch exec [workspace 3 silent] "telegram-desktop"
exec-once = hyprctl dispatch exec [workspace 10 silent] "firefox --new-window https://music.youtube.com"
