#!/usr/bin/env bash

sessions ()
{
    tmux list-sessions -F '#{session_name}' 2>/dev/null \
    | fzf-tmux --exit-0 --reverse --preview 'tmux capture-pane -ep -t {}:1' \
    | xargs -r tmux switch-client -t
}


case "$1" in
    "sessions") sessions
    ;;
esac

